### ISSUE TITLE
Can I talk to it?. 

### ISSUE THREAD

**Issue by josuevalrob** [PalashTanejaPro/BlindHelper#3]
It could be great if I can make some questions directly. 

Like for example, after entering into a biography from Wikipedia, I can ask simple things like: "How Old is she/he?. .

If the information is very well tagged, it could be easy, but even better, if it can contextualize information from the entire web and give me an answer from a simple <p> html tag. 

Good project btw!

**Comment by palash-taneja** [comment]
Hmm not a bad idea, although I think it gets too much into becoming a general assistant that way. Right now if you wanted to accomplish that you could simply ask it to Google for something and open the first link and read the content from there. I get that it's a little more cumbersome but it doesn't lose much on the usability imo. That being said, feel free to fork ahead and add it! I'll help you out if you need me.
